[package]
name = "rutin_proc"
author = "sqfzy"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.5"

[lib]
proc-macro = true
